[package]
name = "toai"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Simple path crawler, that copies all SRC files into a singe output to send it to a ai (toai)"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
globset = "0.4"
arboard = "3.4"
